version: "3.7"
services:
  postgres:
    image: postgres:14.2
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
    - 55432:5432

volumes:
  postgres-data:
